In [ ]:
import torch
from einops import einsum, rearrange

In [13]:
channels_last = torch.randn(64, 32, 32, 3)
B = torch.randn(32 * 32, 32 * 32)


channels_first = rearrange(channels_last, "b h w c -> b c (h w)")

# channels_first = rearrange(
#     channels_last,
#     "batch height width channel -> batch channel (height width)"
#     )

channels_last.shape, channels_first.shape

(torch.Size([64, 32, 32, 3]), torch.Size([64, 3, 1024]))

In [15]:
import torch.nn as nn

nn.Module

torch.nn.modules.module.Module

In [33]:
torch.manual_seed(1234)

x = torch.rand(32, 100, 10)

out = rearrange(einsum(x, "... d_model -> ..."), "... -> ... 1")

print(x[0][0])
print(out[0][0])
out.shape

tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
        0.3315])
tensor([3.3415])


torch.Size([32, 100, 1])

In [17]:
torch.linspace(start=0.0, end=1.0, steps=10)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])